import type { RenderControlValues } from './spiro-types';

export interface SpiroWebglPreset {
  id: string;
  name: string;
  description: string;
  render: Partial<RenderControlValues>;
}

export const DEFAULT_WEBGL_PRESET_ID = 'blue-gray-hologram-ring';

function webglPreset(
  id: string,
  name: string,
  description: string,
  render: Partial<RenderControlValues>
): SpiroWebglPreset {
  return {
    id,
    name,
    description,
    render: {
      ...render,
      webglPreset: id,
    },
  };
}

export const WEBGL_PRESETS: SpiroWebglPreset[] = [
  webglPreset('fin-grain', 'Fin Grain', 'Sharper blue-gray grain for the Fin-style particle dome.', {
    look: 'spiro-grain',
    projectionMode: 'dome',
    projectionBlend: 0.94,
    sphereRadius: 0.92,
    shellThickness: 0.04,
    palette: 'blue-gray',
    order: 0.72,
    voidRadius: 0.12,
    ringThickness: 0.7,
    traceStrength: 0,
    particleCount: 34000,
    particleSize: 1.05,
    particleSoftness: 0.12,
    particleOpacity: 0.42,
    imageRole: 'shape-color',
    imageMaskSource: 'alpha-luminance',
    imageShapePreset: 'auto',
    hologramIntensity: 0.18,
    hologramGlow: 0.18,
    hologramScanlineDensity: 14,
    hologramScanlineSpeed: 0.08,
    hologramShimmer: 0.16,
    hologramNoise: 0.18,
    hologramEdgeFalloff: 0.42,
    hologramChromaticSplit: 0.06,
    hologramColorway: 'blue-gray',
    dimensionality: 0.92,
    domeDepth: 0.72,
    twistDepth: 0.18,
    twistFrequency: 3.4,
    preserveSpiro: 0.86,
    swirl: 0.22,
    turbulence: 0.12,
    rotationX: 54,
    rotationY: 0,
    rotationZ: -8,
    cameraDistance: 7.4,
    cameraFov: 38,
  }),
  webglPreset('data-ring-chaos', 'Data Ring Chaos', 'Noisy annular cloud with a central aperture.', {
    look: 'data-ring',
    projectionMode: 'dome',
    projectionBlend: 0.9,
    sphereRadius: 0.9,
    shellThickness: 0.06,
    palette: 'blue-gray',
    order: 0.18,
    voidRadius: 0.2,
    ringThickness: 0.76,
    traceStrength: 0.08,
    particleCount: 38000,
    particleSize: 0.95,
    particleSoftness: 0.1,
    particleOpacity: 0.38,
    imageRole: 'shape-color',
    imageMaskSource: 'alpha-luminance',
    imageShapePreset: 'cloud',
    hologramIntensity: 0.26,
    hologramGlow: 0.22,
    hologramScanlineDensity: 12,
    hologramScanlineSpeed: 0.16,
    hologramShimmer: 0.24,
    hologramNoise: 0.32,
    hologramEdgeFalloff: 0.54,
    hologramChromaticSplit: 0.08,
    hologramColorway: 'blue-gray',
    dimensionality: 1,
    domeDepth: 0.82,
    twistDepth: 0.14,
    twistFrequency: 4.2,
    preserveSpiro: 0.72,
    swirl: 0.18,
    turbulence: 0.18,
    rotationX: 30,
    rotationY: -4,
    rotationZ: -8,
    cameraDistance: 7.8,
    cameraFov: 36,
  }),
  webglPreset('data-ring-order', 'Data Ring Order', 'Ordered blue-gray ring study inspired by the Figma reference.', {
    look: 'data-ring',
    projectionMode: 'dome',
    projectionBlend: 0.82,
    sphereRadius: 0.9,
    shellThickness: 0.04,
    palette: 'blue-gray',
    order: 0.86,
    voidRadius: 0.32,
    ringThickness: 0.52,
    traceStrength: 0.16,
    particleCount: 42000,
    particleSize: 0.9,
    particleSoftness: 0.09,
    particleOpacity: 0.44,
    imageRole: 'shape-color',
    imageMaskSource: 'alpha-luminance',
    imageShapePreset: 'auto',
    hologramIntensity: 0.22,
    hologramGlow: 0.18,
    hologramScanlineDensity: 18,
    hologramScanlineSpeed: 0.1,
    hologramShimmer: 0.18,
    hologramNoise: 0.16,
    hologramEdgeFalloff: 0.46,
    hologramChromaticSplit: 0.06,
    hologramColorway: 'blue-gray',
    dimensionality: 0.68,
    domeDepth: 0.52,
    twistDepth: 0.12,
    twistFrequency: 5.2,
    preserveSpiro: 0.8,
    swirl: 0.14,
    turbulence: 0.08,
    rotationX: 10,
    rotationY: -6,
    rotationZ: -10,
    cameraDistance: 7.8,
    cameraFov: 36,
  }),
  webglPreset('blue-gray-hologram-ring', 'Blue Gray Hologram Ring', 'Restrained scanline and rim-light layer over the ordered Figma ring.', {
    look: 'data-ring',
    projectionMode: 'hologram-shell',
    projectionBlend: 0.86,
    sphereRadius: 0.86,
    shellThickness: 0.08,
    palette: 'blue-gray',
    order: 0.88,
    voidRadius: 0.32,
    ringThickness: 0.52,
    traceStrength: 0.2,
    particleCount: 42000,
    particleSize: 0.9,
    particleSoftness: 0.08,
    particleOpacity: 0.42,
    imageRole: 'shape-color',
    imageMaskSource: 'alpha-luminance',
    imageShapePreset: 'auto',
    hologramIntensity: 0.48,
    hologramGlow: 0.36,
    hologramScanlineDensity: 22,
    hologramScanlineSpeed: 0.16,
    hologramShimmer: 0.32,
    hologramNoise: 0.22,
    hologramEdgeFalloff: 0.62,
    hologramChromaticSplit: 0.14,
    hologramColorway: 'blue-gray',
    dimensionality: 0.72,
    domeDepth: 0.56,
    twistDepth: 0.13,
    twistFrequency: 5.6,
    preserveSpiro: 0.82,
    swirl: 0.12,
    turbulence: 0.06,
    rotationX: 10,
    rotationY: -6,
    rotationZ: -10,
    cameraDistance: 7.8,
    cameraFov: 36,
  }),
  webglPreset('cyan-shell', 'Cyan Shell', 'Cyan volumetric shell study with brighter front particles.', {
    look: 'data-ring',
    projectionMode: 'hologram-shell',
    projectionBlend: 1,
    sphereRadius: 0.92,
    shellThickness: 0.14,
    palette: 'cyan',
    order: 0.66,
    voidRadius: 0.14,
    ringThickness: 0.72,
    traceStrength: 0.12,
    particleCount: 46000,
    particleSize: 0.95,
    particleSoftness: 0.12,
    particleOpacity: 0.36,
    imageRole: 'shape-color',
    imageMaskSource: 'alpha-luminance',
    imageShapePreset: 'auto',
    hologramIntensity: 0.44,
    hologramGlow: 0.44,
    hologramScanlineDensity: 20,
    hologramScanlineSpeed: 0.2,
    hologramShimmer: 0.34,
    hologramNoise: 0.22,
    hologramEdgeFalloff: 0.68,
    hologramChromaticSplit: 0.18,
    hologramColorway: 'cyan',
    dimensionality: 1.18,
    domeDepth: 1.02,
    twistDepth: 0.24,
    twistFrequency: 4.6,
    preserveSpiro: 0.74,
    swirl: 0.24,
    turbulence: 0.14,
    rotationX: 42,
    rotationY: -10,
    rotationZ: -12,
    cameraDistance: 8.2,
    cameraFov: 34,
  }),
  webglPreset('blue-globe', 'Blue Globe', 'Sphere projection for uploaded globes, maps, planets, and orbital imagery.', {
    look: 'spiro-grain',
    projectionMode: 'sphere',
    projectionBlend: 1,
    sphereRadius: 0.96,
    shellThickness: 0.06,
    palette: 'blue-gray',
    order: 0.72,
    voidRadius: 0.06,
    ringThickness: 0.88,
    traceStrength: 0.04,
    particleCount: 32000,
    particleSize: 0.86,
    particleSoftness: 0.08,
    particleOpacity: 0.46,
    imageRole: 'shape-color',
    imageMaskSource: 'alpha-luminance',
    imageShapePreset: 'globe',
    hologramIntensity: 0.24,
    hologramGlow: 0.18,
    hologramScanlineDensity: 12,
    hologramScanlineSpeed: 0.08,
    hologramShimmer: 0.16,
    hologramNoise: 0.14,
    hologramEdgeFalloff: 0.54,
    hologramChromaticSplit: 0.06,
    hologramColorway: 'blue-gray',
    dimensionality: 1.05,
    domeDepth: 0.52,
    twistDepth: 0.08,
    twistFrequency: 3.4,
    imageDepth: 0.42,
    shapeThreshold: 0.06,
    shapeSoftness: 0.2,
    preserveSpiro: 0.18,
    swirl: 0.08,
    turbulence: 0.06,
    rotationX: 10,
    rotationY: -22,
    rotationZ: -6,
    cameraDistance: 7.2,
    cameraFov: 34,
  }),
  webglPreset(
    'glass-sphere-hologram',
    'Glass Sphere Hologram',
    'Rim-heavy transparent sphere extraction for glass orb renders and cut-out product shells.',
    {
      look: 'spiro-grain',
      projectionMode: 'hologram-shell',
      projectionBlend: 1,
      sphereRadius: 0.94,
      shellThickness: 0.12,
      palette: 'cyan',
      order: 0.7,
      voidRadius: 0.04,
      ringThickness: 0.9,
      traceStrength: 0.05,
      fitMode: 'contain',
      particleCount: 38000,
      particleSize: 0.82,
      particleSoftness: 0.08,
      particleOpacity: 0.42,
      imageRole: 'shape-color',
      imageMaskSource: 'glass',
      imageShapePreset: 'glass-sphere',
      hologramIntensity: 0.54,
      hologramGlow: 0.44,
      hologramScanlineDensity: 18,
      hologramScanlineSpeed: 0.12,
      hologramShimmer: 0.3,
      hologramNoise: 0.18,
      hologramEdgeFalloff: 0.72,
      hologramChromaticSplit: 0.16,
      hologramColorway: 'cyan',
      dimensionality: 1.08,
      domeDepth: 0.62,
      twistDepth: 0.08,
      twistFrequency: 3.6,
      imageDepth: 0.58,
      shapeThreshold: 0.05,
      shapeSoftness: 0.32,
      preserveSpiro: 0.08,
      swirl: 0.07,
      turbulence: 0.05,
      rotationX: 10,
      rotationY: -18,
      rotationZ: -6,
      cameraDistance: 7.2,
      cameraFov: 34,
    }
  ),
  webglPreset('cloud-dome', 'Cloud Dome', 'Soft luminance-shaped dome for cloud, smoke, and atmospheric images.', {
    look: 'spiro-grain',
    projectionMode: 'dome',
    projectionBlend: 0.92,
    sphereRadius: 0.9,
    shellThickness: 0.08,
    palette: 'blue-gray',
    order: 0.42,
    voidRadius: 0.05,
    ringThickness: 0.82,
    traceStrength: 0.04,
    particleCount: 36000,
    particleSize: 1,
    particleSoftness: 0.14,
    particleOpacity: 0.36,
    imageRole: 'shape-color',
    imageMaskSource: 'luminance',
    imageShapePreset: 'cloud',
    hologramIntensity: 0.18,
    hologramGlow: 0.14,
    hologramScanlineDensity: 8,
    hologramScanlineSpeed: 0.05,
    hologramShimmer: 0.14,
    hologramNoise: 0.2,
    hologramEdgeFalloff: 0.42,
    hologramChromaticSplit: 0.04,
    hologramColorway: 'blue-gray',
    dimensionality: 0.78,
    domeDepth: 0.78,
    twistDepth: 0.12,
    twistFrequency: 2.8,
    imageDepth: 0.5,
    shapeThreshold: 0.04,
    shapeSoftness: 0.34,
    preserveSpiro: 0.44,
    swirl: 0.12,
    turbulence: 0.12,
    rotationX: 24,
    rotationY: -8,
    rotationZ: -4,
    cameraDistance: 7.6,
    cameraFov: 36,
  }),
  webglPreset('petal-shell', 'Petal Shell', 'Edge-weighted hologram shell for petals, leaves, and fine silhouettes.', {
    look: 'spiro-grain',
    projectionMode: 'hologram-shell',
    projectionBlend: 0.96,
    sphereRadius: 0.88,
    shellThickness: 0.1,
    palette: 'halo',
    order: 0.68,
    voidRadius: 0.08,
    ringThickness: 0.78,
    traceStrength: 0.08,
    particleCount: 34000,
    particleSize: 0.92,
    particleSoftness: 0.09,
    particleOpacity: 0.44,
    imageRole: 'shape-color',
    imageMaskSource: 'alpha-luminance',
    imageShapePreset: 'petals',
    hologramIntensity: 0.34,
    hologramGlow: 0.24,
    hologramScanlineDensity: 16,
    hologramScanlineSpeed: 0.12,
    hologramShimmer: 0.24,
    hologramNoise: 0.18,
    hologramEdgeFalloff: 0.64,
    hologramChromaticSplit: 0.12,
    hologramColorway: 'halo',
    dimensionality: 0.92,
    domeDepth: 0.68,
    twistDepth: 0.16,
    twistFrequency: 4.4,
    imageDepth: 0.32,
    shapeThreshold: 0.07,
    shapeSoftness: 0.14,
    preserveSpiro: 0.28,
    swirl: 0.18,
    turbulence: 0.08,
    rotationX: 18,
    rotationY: -14,
    rotationZ: -10,
    cameraDistance: 7.4,
    cameraFov: 34,
  }),
];

export const WEBGL_PRESET_OPTIONS = Object.fromEntries(
  WEBGL_PRESETS.map((preset) => [preset.name, preset.id])
) as Record<string, string>;

export function getWebglPresetById(presetId: string): SpiroWebglPreset {
  return WEBGL_PRESETS.find((preset) => preset.id === presetId) ?? WEBGL_PRESETS[0];
}
